export const JOKE_IS_LOADING = 'JOKE_IS_LOADING';
export const JOKE_FETCH_DATA_SUCCESS = 'JOKE_DATA_SUCCESS';
export const JOKE_HAS_ERRORED = 'JOKE_HAS_ERRORED';
export const LIKED_JOKE = 'LIKED_JOKE';
export const DISLIKED_JOKE = 'DISLIKED_JOKE';
export const REMOVE_JOKE = 'REMOVE_JOKE';


